development:
  host: 'localhost:3000'
  username: 'listenlater'
  password: 'test'

test:
  host: 'localhost:3000'
  username: 'listenlater'
  password: 'test'

production:
  host: 'listenlaterapp.com'
  username: 'listenlater'
  password: 'glennsk8'
