development:
  adapter: mysql2
  database: listenlater
  user: root
  password: 

test:
  adapter: mysql2
  database: listenlater_test
  user: root
  password: 

production:
  adapter: mysql2
  database: listenlater_production
  user: root
  password: 
